### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by opooladz** [tlh24/l1-attention#5]
Hi Tim,

Two general questions.

1) What sparsity does the L1 attention achieve compared to DP?

2) In your toy experiments it seems you can remove layer-norm for L1 but not DP. Do you see this at scale? 

Thanks,
Omead

**Comment by tlh24** [comment]
Hi Omead,

1.  There is no clear difference in sparsity or axis-alignment of
features.  That depends more on the optimization algorithm.

2.  That's correct -- DP works with rotations, so it helps that all vectors
are on the surface of a N-1 dimensional sphere.  L1 norm uses the interior
vector space, so LayerNorm or RMSnorm hurts.
We've only tried medium-sized models (dozens of layers), and there doesn't
seem to be obvious instability, but I'm guessing for larger models you
might need to add some regularization on activations (and decay this factor
with time so it doesn't affect ultimate loss).

**Comment by opooladz** [comment]
I see, there are ways to induce sparsity people say (i have not tested myself) like using relu^2 or topk. 

I would like to scale this to some bigger models and see if we can remove normalizations outright. I have never liked normalization layers and this would be good to see if it works at scale. 

I have seen before with removing norm layers that if one uses psgd, it can often lead to better performance vs a first order opt and almost recovers full performance. hopefully with your layer we can fully match performance.

Thank you!
